package com.esiea.androide4a.presentation.main.API

data class Launch (
    public val mission: String? = null,
    public val windowstart: String? = null,
    public val windowend: String? = null,
    public val net: String? = null,
    public val location: String? = null,
    public val countryCode: String? = null,
    public val padname: String? = null,
    public val latitude: String? = null,
    public val longitude: String? = null,
    public val mapURL: String? = null,
    public val padagencies: String? = null,
    public val padabbrev: String? = null,
    public val rocketname: String? = null,
    public val rocketconfiguration: String? = null,
    public val rocketfamilyname: String? = null,
    public val rcname: String? = null,
    public val rcabbrev: String? = null,
    public val rccountryCode: String? = null,
    public val missionname: String? = null,
    public val description: String? = null,
    public val typemission: String? = null,
    public val agenciesname: String? = null,
    public val agenciesabbrev: String? = null,
    public val agenciescountryCode: String? = null,
    public val lspname: String? = null,
    public val lspabbrev: String? = null,
    public val lspcountryCode: String? = null,
    public val fuseeimage: String? = null,
    public val agencyimage: String? = null
){}